spring:
  application:
    name: eazy-bank-backend
logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{yyyy-MM-dd HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger) - %cyan(%msg%n)}
