server:
  port: 8086
spring:
  datasource:
    url: jdbc:h2:mem:spring-security-course
    username: sa
    password: sql
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    "org.springframework.security": ${SPRING_SECURITY_LOG_LEVEL:INFO}
